colors:
  positive: GREEN
  neutral: GRAY
  negative: RED
  botprefix: AQUA
irc:
  server: irc.esper.net
  port: 6667
  nick: Wheatley
  user: Wheatley
  serverpass: ''
  nickservpass: ''
  channels:
    - "#wheatley"
  staffchannel:
    - "#wheatley-staff"
  autoreconnect: true