main: com.applecraftserver.plugins.core.Core
name: core
author: AppleCraft team
version: b1
load: STARTUP
#database: true
commands:
  plugin:
    description: Manage plugins installed on the server
    usage: /<command> [subcommands]